import xlsx from 'xlsx';
import path from 'path';
import fs from 'fs';

// 1. Data for ERE (55 personnel from Page 1)
const ERE_LIST = [
  { ser: 1, snkNo: '1227660', rk: 'Sgt', trade: 'DMT', name: 'Md. Anwarul Islam', bty: 'HQ Bty' },
  { ser: 2, snkNo: '1239183', rk: 'Snk', trade: 'Ck(U)', name: 'Md. Aziz', bty: 'P Bty' },
  { ser: 3, snkNo: '1244672', rk: 'Snk', trade: 'Gnr', name: 'Md. Sujon Daria', bty: 'R Bty' },
  { ser: 4, snkNo: '1234815', rk: 'Lcpl', trade: 'Gnr', name: 'Ariful Islam (Rajib)', bty: 'R Bty' },
  { ser: 5, snkNo: '1238577', rk: 'Snk', trade: 'Gnr', name: 'Rubel Hossain', bty: 'Q Bty' },
  { ser: 6, snkNo: '1245970', rk: 'Snk', trade: 'Gnr', name: 'Md. Khorshed Alam', bty: 'P Bty' },
  { ser: 7, snkNo: '1227682', rk: 'Cpl', trade: 'Ck(U)', name: 'Md. Babul Hossain', bty: 'P Bty' },
  { ser: 8, snkNo: '1224584', rk: 'NC(E)', trade: 'NC(E)', name: 'Md. Afaz Uddin', bty: 'HQ Bty' },
  { ser: 9, snkNo: '1238220', rk: 'Snk', trade: 'TA', name: 'Idris Amin', bty: 'Q Bty' },
  { ser: 10, snkNo: '1242278', rk: 'Snk', trade: 'DMT', name: 'Md. Ziaur Rahman', bty: 'R Bty' },
  { ser: 11, snkNo: '1240483', rk: 'Snk', trade: 'DMT', name: 'Md. Himel', bty: 'R Bty' },
  { ser: 12, snkNo: '1246024', rk: 'Snk', trade: 'Gnr', name: 'Md. Fazle Rabbi', bty: 'Q Bty' },
  { ser: 13, snkNo: '1238563', rk: 'Snk', trade: 'DMT', name: 'Pollob Kumar Bormon', bty: 'HQ Bty' },
  { ser: 14, snkNo: '1244306', rk: 'Snk', trade: 'Gnr', name: 'Md. Shamim Hawladar', bty: 'R Bty' },
  { ser: 15, snkNo: '1240404', rk: 'Snk', trade: 'DMT', name: 'Md. Joni Alom', bty: 'HQ Bty' },
  { ser: 16, snkNo: '1247857', rk: 'Snk', trade: 'Gnr', name: 'Tarek Mia', bty: 'Q Bty' },
  { ser: 17, snkNo: 'BJO-Noya-1', rk: 'WO', trade: 'Gnr', name: 'Khurshid Alam', bty: 'R Bty' },
  { ser: 18, snkNo: '1229288', rk: 'Cpl', trade: 'Gnr', name: 'Md. Sohag Molla', bty: 'Q Bty' },
  { ser: 19, snkNo: '1225490', rk: 'Sgt', trade: 'Gnr', name: 'Md. Shamim Shahria', bty: 'R Bty' },
  { ser: 20, snkNo: '1226694', rk: 'Sgt', trade: 'Gnr', name: 'Md. Arif Hossen', bty: 'P Bty' },
  { ser: 21, snkNo: '1230480', rk: 'Cpl', trade: 'Gnr', name: 'Md. Shahin Alam', bty: 'Q Bty' },
  { ser: 22, snkNo: '1223852', rk: 'Sgt', trade: 'Gnr', name: 'Md. Yusuf', bty: 'Q Bty' },
  { ser: 23, snkNo: '1228391', rk: 'Cpl', trade: 'Gnr', name: 'Md. Anisur Rahman', bty: 'Q Bty' },
  { ser: 24, snkNo: '1240547', rk: 'Snk', trade: 'Gnr', name: 'Md. Jakir Hossen', bty: 'Q Bty' },
  { ser: 25, snkNo: '1246179', rk: 'Snk', trade: 'Gnr', name: 'Md. Farhad Hasan', bty: 'P Bty' },
  { ser: 26, snkNo: '1234588', rk: 'Lcpl', trade: 'Gnr', name: 'Md. Amir Hossen', bty: 'R Bty' },
  { ser: 27, snkNo: '1229574', rk: 'Cpl', trade: 'Gnr', name: 'Md. Mottalib Hossen', bty: 'HQ Bty' },
  { ser: 28, snkNo: '1240267', rk: 'Snk', trade: 'OCU', name: 'Md. Golam Azam', bty: 'R Bty' },
  { ser: 29, snkNo: '1224246', rk: 'Sgt', trade: 'DMT', name: 'Md. Shahin Alam', bty: 'HQ Bty' },
  { ser: 30, snkNo: '1231727', rk: 'Cpl', trade: 'DMT', name: 'Md. Faruk Amin', bty: 'R Bty' },
  { ser: 31, snkNo: '1230012', rk: 'Cpl', trade: 'Gnr', name: 'Md. Mahbub Alam', bty: 'R Bty' },
  { ser: 32, snkNo: '1245360', rk: 'Snk', trade: 'OCU', name: 'Md. Shahidul Islam', bty: 'HQ Bty' },
  { ser: 33, snkNo: 'BJO-Noya-2', rk: 'WO', trade: 'Gnr', name: 'Md. Liakot Ali', bty: 'R Bty' },
  { ser: 34, snkNo: '1227667', rk: 'Cpl', trade: 'Ck(U)', name: 'Md. Ansar Ali', bty: 'HQ Bty' },
  { ser: 35, snkNo: '1238878', rk: 'Snk', trade: 'DMT', name: 'Md. Mamun Hossen', bty: 'HQ Bty' },
  { ser: 36, snkNo: '1240568', rk: 'Snk', trade: 'DMT', name: 'Md. Shoukhin Mia', bty: 'P Bty' },
  { ser: 37, snkNo: '1238461', rk: 'Snk', trade: 'DMT', name: 'Md. Sakib Hossain', bty: 'Q Bty' },
  { ser: 38, snkNo: '1232649', rk: 'Lcpl', trade: 'Ck(U)', name: 'Md. Rouful Islam', bty: 'R Bty' },
  { ser: 39, snkNo: '1239977', rk: 'Snk', trade: 'TA', name: 'Md. Shahidul Islam', bty: 'HQ Bty' },
  { ser: 40, snkNo: '1230332', rk: 'Cpl', trade: 'Gnr', name: 'Md. Abu Sayed', bty: 'R Bty' },
  { ser: 41, snkNo: '1230951', rk: 'Cpl', trade: 'OCU', name: 'Md. Mominul Bhuiyan', bty: 'R Bty' },
  { ser: 42, snkNo: '1241140', rk: 'Snk', trade: 'DMT', name: 'Md. Rakib Hasan', bty: 'HQ Bty' },
  { ser: 43, snkNo: '1235106', rk: 'Lcpl', trade: 'OCU', name: 'Md. Rayfan Jani', bty: 'Q Bty' },
  { ser: 44, snkNo: '1230807', rk: 'Cpl', trade: 'Gnr', name: 'Md. Rubel Rana', bty: 'Q Bty' },
  { ser: 45, snkNo: '1228857', rk: 'Cpl', trade: 'Gnr', name: 'Md. Al Amin', bty: 'Q Bty' },
  { ser: 46, snkNo: '1224496', rk: 'Cpl', trade: 'Ck(U)', name: 'Md. Shahin Aktar', bty: 'Q Bty' },
  { ser: 47, snkNo: '1230777', rk: 'Cpl', trade: 'OCU', name: 'Md. Saiful Islam', bty: 'HQ Bty' },
  { ser: 48, snkNo: '1228146', rk: 'Cpl', trade: 'Gnr', name: 'Md. Jasim Uddin', bty: 'Q Bty' },
  { ser: 49, snkNo: '1229588', rk: 'Cpl', trade: 'DMT', name: 'Sujon Mia', bty: 'Q Bty' },
  { ser: 50, snkNo: '1228132', rk: 'Sgt', trade: 'Gnr', name: 'Md. Mostafa Kamal', bty: 'R Bty' },
  { ser: 51, snkNo: '1239580', rk: 'Snk', trade: 'DMT', name: 'Md. Rakib Sheikh', bty: 'Q Bty' },
  { ser: 52, snkNo: '1230804', rk: 'Cpl', trade: 'Gnr', name: 'Md. Rashadul Islam', bty: 'Q Bty' },
  { ser: 53, snkNo: '1228535', rk: 'Cpl', trade: 'Gnr', name: 'Md. Majedul Islam', bty: 'Q Bty' },
  { ser: 54, snkNo: '1230830', rk: 'Cpl', trade: 'DMT', name: 'Md. Yusuf Ali', bty: 'R Bty' },
  { ser: 55, snkNo: '1226409', rk: 'Sgt', trade: 'Gnr', name: 'Md. Abdur Razzak Sujon', bty: 'Q Bty' },
];

// 2. Data for Att / Permanent Attached (46 personnel from Page 2)
const ATT_LIST = [
  { ser: 1, snkNo: '1227569', rk: 'Cpl', trade: 'Gnr', name: 'Ganesh Chandra Sarkar', bty: 'P Bty' },
  { ser: 2, snkNo: '1237000', rk: 'Snk', trade: 'Gnr', name: 'Md. Hashan Shikh', bty: 'P Bty' },
  { ser: 3, snkNo: '1243059', rk: 'Snk', trade: 'Gnr', name: 'Nayeem Hawladar', bty: 'P Bty' },
  { ser: 4, snkNo: '1228334', rk: 'Lcpl', trade: 'Gnr', name: 'Md. Zuel Rana', bty: 'Q Bty' },
  { ser: 5, snkNo: '1250885', rk: 'Snk', trade: 'OCU', name: 'Md. Imran Islam', bty: 'P Bty' },
  { ser: 6, snkNo: '1228353', rk: 'Cpl', trade: 'Gnr', name: 'Md. Zuel Rana', bty: 'Q Bty' },
  { ser: 7, snkNo: '1243678', rk: 'Snk', trade: 'Gnr', name: 'Md. Maksudur Alam', bty: 'Q Bty' },
  { ser: 8, snkNo: '1245478', rk: 'Snk', trade: 'OCU', name: 'Md. Shamsuddin', bty: 'Q Bty' },
  { ser: 9, snkNo: '1245308', rk: 'Snk', trade: 'OCU', name: 'Md. Sojib Sheikh', bty: 'R Bty' },
  { ser: 10, snkNo: '1248561', rk: 'Snk', trade: 'OCU', name: 'Md. Mehedi Hasan', bty: 'HQ Bty' },
  { ser: 11, snkNo: '1249167', rk: 'Snk', trade: 'Gnr', name: 'Md. Mehedy Hasan', bty: 'HQ Bty' },
  { ser: 12, snkNo: '1228491', rk: 'Cpl', trade: 'DMT', name: 'Md. Mainul Islam Sikdar', bty: 'Q Bty' },
  { ser: 13, snkNo: '1228564', rk: 'Cpl', trade: 'Gnr', name: 'Md. Anisuzzaman', bty: 'P Bty' },
  { ser: 14, snkNo: '1224126', rk: 'Sgt', trade: 'DMT', name: 'Md. Amanul Islam Gazi', bty: 'Q Bty' },
  { ser: 15, snkNo: '1223752', rk: 'Sgt', trade: 'TA', name: 'Md. Masudur Rahman', bty: 'R Bty' },
  { ser: 16, snkNo: '1249464', rk: 'Snk', trade: 'DMT', name: 'Md. Sakib Hasan', bty: 'HQ Bty' },
  { ser: 17, snkNo: '1249715', rk: 'Snk', trade: 'Gnr', name: 'Md. Masud Khan', bty: 'HQ Bty' },
  { ser: 18, snkNo: '1226084', rk: 'Sgt', trade: 'Gnr', name: 'Md. Mohsin Ali', bty: 'R Bty' },
  { ser: 19, snkNo: '1229513', rk: 'Cpl', trade: 'DMT', name: 'Md. Rashid Khan', bty: 'R Bty' },
  { ser: 20, snkNo: '1248817', rk: 'Snk', trade: 'Gnr', name: 'Shahadat Hossain', bty: 'R Bty' },
  { ser: 21, snkNo: '1230301', rk: 'Cpl', trade: 'Gnr', name: 'Md. Nazmul Alom', bty: 'P Bty' },
  { ser: 22, snkNo: '1231256', rk: 'Lcpl', trade: 'Gnr', name: 'Md. Abu Sayed', bty: 'R Bty' },
  { ser: 23, snkNo: '1223966', rk: 'Sgt', trade: 'DMT', name: 'Md. Shahidul Islam', bty: 'HQ Bty' },
  { ser: 24, snkNo: '1231696', rk: 'Cpl', trade: 'TA', name: 'Md. Arif Hossain', bty: 'R Bty' },
  { ser: 25, snkNo: '1233437', rk: 'Cpl', trade: 'Gnr', name: 'Md. Towsik Hassan Sobuz', bty: 'Q Bty' },
  { ser: 26, snkNo: '1226077', rk: 'Sgt', trade: 'TA', name: 'Al Amin', bty: 'R Bty' },
  { ser: 27, snkNo: '1234871', rk: 'Lcpl', trade: 'DMT', name: 'Mohammad Omar Faruk', bty: 'P Bty' },
  { ser: 28, snkNo: '1233271', rk: 'Cpl', trade: 'TA', name: 'Mohah Saddam Hossain', bty: 'Q Bty' },
  { ser: 29, snkNo: '1243014', rk: 'Snk', trade: 'Gnr', name: 'Md. Selim Ahmed', bty: 'Q Bty' },
  { ser: 30, snkNo: '1234845', rk: 'Snk', trade: 'Ck(U)', name: 'Md. Riton Mia', bty: 'P Bty' },
  { ser: 31, snkNo: '1233541', rk: 'Cpl', trade: 'Gnr', name: 'Al Amin', bty: 'Q Bty' },
  { ser: 32, snkNo: '1229555', rk: 'Cpl', trade: 'DMT', name: 'Md. Moinul Islam', bty: 'HQ Bty' },
  { ser: 33, snkNo: '1227551', rk: 'Sgt', trade: 'Gnr', name: 'Md. Bulbul Choudary', bty: 'P Bty' },
  { ser: 34, snkNo: '1234039', rk: 'Lcpl', trade: 'OCU', name: 'Md. Maruf Mia', bty: 'P Bty' },
  { ser: 35, snkNo: '1235893', rk: 'Lcpl', trade: 'Gnr', name: 'Md. Shahin Alam', bty: 'HQ Bty' },
  { ser: 36, snkNo: '1230375', rk: 'Cpl', trade: 'Gnr', name: 'Md. Al Amin', bty: 'P Bty' },
  { ser: 37, snkNo: '1243307', rk: 'Snk', trade: 'TA', name: 'Mohammad Salman Shah', bty: 'Q Bty' },
  { ser: 38, snkNo: '1228053', rk: 'Cpl', trade: 'Gnr', name: 'Md. Alamgir Hossen', bty: 'R Bty' },
  { ser: 39, snkNo: '1245368', rk: 'NC(E)', trade: 'NC(E)', name: 'Md. Sabbir Ahmed', bty: 'HQ Bty' },
  { ser: 40, snkNo: '1228519', rk: 'Cpl', trade: 'Gnr', name: 'Farid', bty: 'R Bty' },
  { ser: 41, snkNo: '1235947', rk: 'Lcpl', trade: 'Gnr', name: 'Sobuj Biswas', bty: 'Q Bty' },
  { ser: 42, snkNo: '1247073', rk: 'Snk', trade: 'Gnr', name: 'Khaledul Hasan Milu', bty: 'Q Bty' },
  { ser: 43, snkNo: '1247140', rk: 'Snk', trade: 'Gnr', name: 'Md. Anisur Rahman Akash', bty: 'R Bty' },
  { ser: 44, snkNo: '1250972', rk: 'Snk', trade: 'Gnr', name: 'Md. Hridoy Hossain', bty: 'P Bty' },
  { ser: 45, snkNo: '1237663', rk: 'Snk', trade: 'OCU', name: 'Md. Rifat', bty: 'P Bty' },
  { ser: 46, snkNo: 'BJO-Noya-3', rk: 'WO', trade: 'Gnr', name: 'Md. Mamun Sikder', bty: 'R Bty' },
];

// 3. Data for Msn (13 personnel from Page 3)
const MSN_LIST = [
  { ser: 1, snkNo: '1231157', rk: 'Cpl', trade: 'DMT', name: 'Md. Mosleh Uddin', bty: 'P Bty' },
  { ser: 2, snkNo: '1231631', rk: 'Cpl', trade: 'DMT', name: 'Md. Munjurul', bty: 'P Bty' },
  { ser: 3, snkNo: '1229605', rk: 'Cpl', trade: 'DMT', name: 'Monjurul Haque', bty: 'P Bty' },
  { ser: 4, snkNo: '1231940', rk: 'Cpl', trade: 'OCU', name: 'Md. Masud Rana', bty: 'P Bty' },
  { ser: 5, snkNo: '1229492', rk: 'Cpl', trade: 'DMT', name: 'Md. Alamgir Sarkar', bty: 'P Bty' },
  { ser: 6, snkNo: '1229205', rk: 'Cpl', trade: 'DMT', name: 'Moksedul Haque', bty: 'Q Bty' },
  { ser: 7, snkNo: '1229445', rk: 'Cpl', trade: 'DMT', name: 'Md. Golam Rahman', bty: 'Q Bty' },
  { ser: 8, snkNo: '1229470', rk: 'Cpl', trade: 'DMT', name: 'Abdul Baten', bty: 'Q Bty' },
  { ser: 9, snkNo: '1234220', rk: 'Lcpl', trade: 'TA', name: 'Md. Arfan Islam', bty: 'R Bty' },
  { ser: 10, snkNo: '1236755', rk: 'Snk', trade: 'Gnr', name: 'Md. Saidul Islam', bty: 'P Bty' },
  { ser: 11, snkNo: '1226976', rk: 'Cpl', trade: 'Gnr', name: 'Md. Motiar Rahaman', bty: 'Q Bty' },
  { ser: 12, snkNo: '1231760', rk: 'Lcpl', trade: 'TA', name: 'Sk Tusheruzzaman', bty: 'P Bty' },
  { ser: 13, snkNo: '1228732', rk: 'Lcpl', trade: 'Gnr', name: 'Md. Sabuj Ali', bty: 'R Bty' },
];

console.log('ERE Count:', ERE_LIST.length);
console.log('Att Count:', ATT_LIST.length);
console.log('Msn Count:', MSN_LIST.length);
